//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Users/Sheep/Documents/CodeCrafters/codecrafters-shell-csharp/src/ArgParsing/Command.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace CodeCrafters.Shell.ArgParsing {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public partial class CommandLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		ESCAPE=1, SSTRING=2, DSTRING=3, UNQUOTED=4, D_SQUOTE=5, D_DQUOTE=6, WS=7;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"ESCAPE", "SSTRING", "DSTRING", "UNQUOTED", "D_SQUOTE", "D_DQUOTE", "WS"
	};


	public CommandLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public CommandLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, null, null, null, null, "''''", "'\"\"'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "ESCAPE", "SSTRING", "DSTRING", "UNQUOTED", "D_SQUOTE", "D_DQUOTE", 
		"WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Command.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static CommandLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static int[] _serializedATN = {
		4,0,7,54,6,-1,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,
		1,0,1,0,1,0,1,1,1,1,1,1,1,1,4,1,23,8,1,11,1,12,1,24,1,1,1,1,1,2,1,2,1,
		2,1,2,4,2,33,8,2,11,2,12,2,34,1,2,1,2,1,3,4,3,40,8,3,11,3,12,3,41,1,4,
		1,4,1,4,1,5,1,5,1,5,1,6,4,6,51,8,6,11,6,12,6,52,0,0,7,1,1,3,2,5,3,7,4,
		9,5,11,6,13,7,1,0,4,2,0,39,39,92,92,2,0,34,34,92,92,6,0,9,10,13,13,32,
		32,34,34,39,39,92,92,3,0,9,10,13,13,32,32,59,0,1,1,0,0,0,0,3,1,0,0,0,0,
		5,1,0,0,0,0,7,1,0,0,0,0,9,1,0,0,0,0,11,1,0,0,0,0,13,1,0,0,0,1,15,1,0,0,
		0,3,18,1,0,0,0,5,28,1,0,0,0,7,39,1,0,0,0,9,43,1,0,0,0,11,46,1,0,0,0,13,
		50,1,0,0,0,15,16,5,92,0,0,16,17,9,0,0,0,17,2,1,0,0,0,18,22,5,39,0,0,19,
		20,5,92,0,0,20,23,5,39,0,0,21,23,8,0,0,0,22,19,1,0,0,0,22,21,1,0,0,0,23,
		24,1,0,0,0,24,22,1,0,0,0,24,25,1,0,0,0,25,26,1,0,0,0,26,27,5,39,0,0,27,
		4,1,0,0,0,28,32,5,34,0,0,29,30,5,92,0,0,30,33,5,34,0,0,31,33,8,1,0,0,32,
		29,1,0,0,0,32,31,1,0,0,0,33,34,1,0,0,0,34,32,1,0,0,0,34,35,1,0,0,0,35,
		36,1,0,0,0,36,37,5,34,0,0,37,6,1,0,0,0,38,40,8,2,0,0,39,38,1,0,0,0,40,
		41,1,0,0,0,41,39,1,0,0,0,41,42,1,0,0,0,42,8,1,0,0,0,43,44,5,39,0,0,44,
		45,5,39,0,0,45,10,1,0,0,0,46,47,5,34,0,0,47,48,5,34,0,0,48,12,1,0,0,0,
		49,51,7,3,0,0,50,49,1,0,0,0,51,52,1,0,0,0,52,50,1,0,0,0,52,53,1,0,0,0,
		53,14,1,0,0,0,7,0,22,24,32,34,41,52,0
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace CodeCrafters.Shell.ArgParsing
