//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Users/Sheep/Documents/CodeCrafters/codecrafters-shell-csharp/src/ArgParsing/Command.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace CodeCrafters.Shell.ArgParsing {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ICommandListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class CommandBaseListener : ICommandListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="CommandParser.cmd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCmd([NotNull] CommandParser.CmdContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CommandParser.cmd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCmd([NotNull] CommandParser.CmdContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CommandParser.arg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArg([NotNull] CommandParser.ArgContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CommandParser.arg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArg([NotNull] CommandParser.ArgContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>EscapeCharacter</c>
	/// labeled alternative in <see cref="CommandParser.str"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEscapeCharacter([NotNull] CommandParser.EscapeCharacterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>EscapeCharacter</c>
	/// labeled alternative in <see cref="CommandParser.str"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEscapeCharacter([NotNull] CommandParser.EscapeCharacterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>UnquotedString</c>
	/// labeled alternative in <see cref="CommandParser.str"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnquotedString([NotNull] CommandParser.UnquotedStringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>UnquotedString</c>
	/// labeled alternative in <see cref="CommandParser.str"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnquotedString([NotNull] CommandParser.UnquotedStringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>SingleQuotedString</c>
	/// labeled alternative in <see cref="CommandParser.str"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSingleQuotedString([NotNull] CommandParser.SingleQuotedStringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>SingleQuotedString</c>
	/// labeled alternative in <see cref="CommandParser.str"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSingleQuotedString([NotNull] CommandParser.SingleQuotedStringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>DoubleQuotedString</c>
	/// labeled alternative in <see cref="CommandParser.str"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDoubleQuotedString([NotNull] CommandParser.DoubleQuotedStringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>DoubleQuotedString</c>
	/// labeled alternative in <see cref="CommandParser.str"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDoubleQuotedString([NotNull] CommandParser.DoubleQuotedStringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>SingleStringText</c>
	/// labeled alternative in <see cref="CommandParser.sstr_inner"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSingleStringText([NotNull] CommandParser.SingleStringTextContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>SingleStringText</c>
	/// labeled alternative in <see cref="CommandParser.sstr_inner"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSingleStringText([NotNull] CommandParser.SingleStringTextContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>DoubleStringEscapeCharacter</c>
	/// labeled alternative in <see cref="CommandParser.dstr_inner"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDoubleStringEscapeCharacter([NotNull] CommandParser.DoubleStringEscapeCharacterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>DoubleStringEscapeCharacter</c>
	/// labeled alternative in <see cref="CommandParser.dstr_inner"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDoubleStringEscapeCharacter([NotNull] CommandParser.DoubleStringEscapeCharacterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>DoubleStringText</c>
	/// labeled alternative in <see cref="CommandParser.dstr_inner"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDoubleStringText([NotNull] CommandParser.DoubleStringTextContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>DoubleStringText</c>
	/// labeled alternative in <see cref="CommandParser.dstr_inner"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDoubleStringText([NotNull] CommandParser.DoubleStringTextContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace CodeCrafters.Shell.ArgParsing
