//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Users/Sheep/Documents/CodeCrafters/codecrafters-shell-csharp/src/ArgParsing/Command.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace CodeCrafters.Shell.ArgParsing {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="CommandParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface ICommandVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="CommandParser.cmd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCmd([NotNull] CommandParser.CmdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CommandParser.arg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArg([NotNull] CommandParser.ArgContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EscapeCharacter</c>
	/// labeled alternative in <see cref="CommandParser.str"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEscapeCharacter([NotNull] CommandParser.EscapeCharacterContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UnquotedString</c>
	/// labeled alternative in <see cref="CommandParser.str"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnquotedString([NotNull] CommandParser.UnquotedStringContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SingleQuotedString</c>
	/// labeled alternative in <see cref="CommandParser.str"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSingleQuotedString([NotNull] CommandParser.SingleQuotedStringContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DoubleQuotedString</c>
	/// labeled alternative in <see cref="CommandParser.str"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDoubleQuotedString([NotNull] CommandParser.DoubleQuotedStringContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SingleStringText</c>
	/// labeled alternative in <see cref="CommandParser.sstr_inner"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSingleStringText([NotNull] CommandParser.SingleStringTextContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DoubleStringEscapeCharacter</c>
	/// labeled alternative in <see cref="CommandParser.dstr_inner"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDoubleStringEscapeCharacter([NotNull] CommandParser.DoubleStringEscapeCharacterContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DoubleStringText</c>
	/// labeled alternative in <see cref="CommandParser.dstr_inner"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDoubleStringText([NotNull] CommandParser.DoubleStringTextContext context);
}
} // namespace CodeCrafters.Shell.ArgParsing
