//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Users/Sheep/Documents/CodeCrafters/codecrafters-shell-csharp/src/ArgParsing/Command.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace CodeCrafters.Shell.ArgParsing {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public partial class CommandLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		SSTRING=1, DSTRING=2, UNQUOTED=3, D_SQUOTE=4, D_DQUOTE=5, WS=6;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"SSTRING", "DSTRING", "UNQUOTED", "D_SQUOTE", "D_DQUOTE", "WS"
	};


	public CommandLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public CommandLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, null, null, null, "''''", "'\"\"'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "SSTRING", "DSTRING", "UNQUOTED", "D_SQUOTE", "D_DQUOTE", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Command.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static CommandLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static int[] _serializedATN = {
		4,0,6,49,6,-1,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,1,0,1,0,
		4,0,16,8,0,11,0,12,0,17,1,0,1,0,1,1,1,1,4,1,24,8,1,11,1,12,1,25,1,1,1,
		1,1,2,4,2,31,8,2,11,2,12,2,32,1,3,1,3,1,3,1,3,1,3,1,4,1,4,1,4,1,4,1,4,
		1,5,4,5,46,8,5,11,5,12,5,47,0,0,6,1,1,3,2,5,3,7,4,9,5,11,6,1,0,4,1,0,39,
		39,1,0,34,34,5,0,9,10,13,13,32,32,34,34,39,39,3,0,9,10,13,13,32,32,52,
		0,1,1,0,0,0,0,3,1,0,0,0,0,5,1,0,0,0,0,7,1,0,0,0,0,9,1,0,0,0,0,11,1,0,0,
		0,1,13,1,0,0,0,3,21,1,0,0,0,5,30,1,0,0,0,7,34,1,0,0,0,9,39,1,0,0,0,11,
		45,1,0,0,0,13,15,5,39,0,0,14,16,8,0,0,0,15,14,1,0,0,0,16,17,1,0,0,0,17,
		15,1,0,0,0,17,18,1,0,0,0,18,19,1,0,0,0,19,20,5,39,0,0,20,2,1,0,0,0,21,
		23,5,34,0,0,22,24,8,1,0,0,23,22,1,0,0,0,24,25,1,0,0,0,25,23,1,0,0,0,25,
		26,1,0,0,0,26,27,1,0,0,0,27,28,5,34,0,0,28,4,1,0,0,0,29,31,8,2,0,0,30,
		29,1,0,0,0,31,32,1,0,0,0,32,30,1,0,0,0,32,33,1,0,0,0,33,6,1,0,0,0,34,35,
		5,39,0,0,35,36,5,39,0,0,36,37,1,0,0,0,37,38,6,3,0,0,38,8,1,0,0,0,39,40,
		5,34,0,0,40,41,5,34,0,0,41,42,1,0,0,0,42,43,6,4,0,0,43,10,1,0,0,0,44,46,
		7,3,0,0,45,44,1,0,0,0,46,47,1,0,0,0,47,45,1,0,0,0,47,48,1,0,0,0,48,12,
		1,0,0,0,5,0,17,25,32,47,1,6,0,0
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace CodeCrafters.Shell.ArgParsing
