//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Users/Sheep/Documents/CodeCrafters/codecrafters-shell-csharp/src/ArgParsing/Command.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace CodeCrafters.Shell.ArgParsing {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="CommandParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface ICommandListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="CommandParser.cmd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCmd([NotNull] CommandParser.CmdContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CommandParser.cmd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCmd([NotNull] CommandParser.CmdContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CommandParser.arg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArg([NotNull] CommandParser.ArgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CommandParser.arg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArg([NotNull] CommandParser.ArgContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CommandParser.red"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRed([NotNull] CommandParser.RedContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CommandParser.red"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRed([NotNull] CommandParser.RedContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CommandParser.red_stream"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRed_stream([NotNull] CommandParser.Red_streamContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CommandParser.red_stream"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRed_stream([NotNull] CommandParser.Red_streamContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CommandParser.red_op"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRed_op([NotNull] CommandParser.Red_opContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CommandParser.red_op"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRed_op([NotNull] CommandParser.Red_opContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EscapeCharacter</c>
	/// labeled alternative in <see cref="CommandParser.str"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEscapeCharacter([NotNull] CommandParser.EscapeCharacterContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EscapeCharacter</c>
	/// labeled alternative in <see cref="CommandParser.str"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEscapeCharacter([NotNull] CommandParser.EscapeCharacterContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>UnquotedString</c>
	/// labeled alternative in <see cref="CommandParser.str"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnquotedString([NotNull] CommandParser.UnquotedStringContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>UnquotedString</c>
	/// labeled alternative in <see cref="CommandParser.str"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnquotedString([NotNull] CommandParser.UnquotedStringContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>SingleQuotedString</c>
	/// labeled alternative in <see cref="CommandParser.str"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSingleQuotedString([NotNull] CommandParser.SingleQuotedStringContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>SingleQuotedString</c>
	/// labeled alternative in <see cref="CommandParser.str"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSingleQuotedString([NotNull] CommandParser.SingleQuotedStringContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>DoubleQuotedString</c>
	/// labeled alternative in <see cref="CommandParser.str"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDoubleQuotedString([NotNull] CommandParser.DoubleQuotedStringContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>DoubleQuotedString</c>
	/// labeled alternative in <see cref="CommandParser.str"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDoubleQuotedString([NotNull] CommandParser.DoubleQuotedStringContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>SingleStringText</c>
	/// labeled alternative in <see cref="CommandParser.sstr_inner"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSingleStringText([NotNull] CommandParser.SingleStringTextContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>SingleStringText</c>
	/// labeled alternative in <see cref="CommandParser.sstr_inner"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSingleStringText([NotNull] CommandParser.SingleStringTextContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>DoubleStringEscapeCharacter</c>
	/// labeled alternative in <see cref="CommandParser.dstr_inner"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDoubleStringEscapeCharacter([NotNull] CommandParser.DoubleStringEscapeCharacterContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>DoubleStringEscapeCharacter</c>
	/// labeled alternative in <see cref="CommandParser.dstr_inner"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDoubleStringEscapeCharacter([NotNull] CommandParser.DoubleStringEscapeCharacterContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>DoubleStringText</c>
	/// labeled alternative in <see cref="CommandParser.dstr_inner"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDoubleStringText([NotNull] CommandParser.DoubleStringTextContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>DoubleStringText</c>
	/// labeled alternative in <see cref="CommandParser.dstr_inner"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDoubleStringText([NotNull] CommandParser.DoubleStringTextContext context);
}
} // namespace CodeCrafters.Shell.ArgParsing
