//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Users/Sheep/Documents/CodeCrafters/codecrafters-shell-csharp/src/ArgParsing/Command.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace CodeCrafters.Shell.ArgParsing {
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public partial class CommandParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		WS=1, SQUOTE=2, DQUOTE=3, SLASH=4, NUMBER=5, REDIRECT=6, NON_WS=7;
	public const int
		RULE_cmd = 0, RULE_arg = 1, RULE_red = 2, RULE_red_stream = 3, RULE_red_op = 4, 
		RULE_str = 5, RULE_sstr_inner = 6, RULE_dstr_inner = 7;
	public static readonly string[] ruleNames = {
		"cmd", "arg", "red", "red_stream", "red_op", "str", "sstr_inner", "dstr_inner"
	};

	private static readonly string[] _LiteralNames = {
		null, null, "'''", "'\"'", "'\\'", null, "'>'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "WS", "SQUOTE", "DQUOTE", "SLASH", "NUMBER", "REDIRECT", "NON_WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Command.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static CommandParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public CommandParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public CommandParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class CmdContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ArgContext[] arg() {
			return GetRuleContexts<ArgContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ArgContext arg(int i) {
			return GetRuleContext<ArgContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(CommandParser.Eof, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public RedContext[] red() {
			return GetRuleContexts<RedContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public RedContext red(int i) {
			return GetRuleContext<RedContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] WS() { return GetTokens(CommandParser.WS); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WS(int i) {
			return GetToken(CommandParser.WS, i);
		}
		public CmdContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_cmd; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ICommandListener typedListener = listener as ICommandListener;
			if (typedListener != null) typedListener.EnterCmd(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ICommandListener typedListener = listener as ICommandListener;
			if (typedListener != null) typedListener.ExitCmd(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICommandVisitor<TResult> typedVisitor = visitor as ICommandVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCmd(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CmdContext cmd() {
		CmdContext _localctx = new CmdContext(Context, State);
		EnterRule(_localctx, 0, RULE_cmd);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 16;
			arg();
			State = 25;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,1,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 18;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
					do {
						{
						{
						State = 17;
						Match(WS);
						}
						}
						State = 20;
						ErrorHandler.Sync(this);
						_la = TokenStream.LA(1);
					} while ( _la==WS );
					State = 22;
					arg();
					}
					} 
				}
				State = 27;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,1,Context);
			}
			State = 36;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==WS) {
				{
				{
				State = 29;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				do {
					{
					{
					State = 28;
					Match(WS);
					}
					}
					State = 31;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				} while ( _la==WS );
				State = 33;
				red();
				}
				}
				State = 38;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 39;
			Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArgContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public StrContext[] str() {
			return GetRuleContexts<StrContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StrContext str(int i) {
			return GetRuleContext<StrContext>(i);
		}
		public ArgContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arg; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ICommandListener typedListener = listener as ICommandListener;
			if (typedListener != null) typedListener.EnterArg(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ICommandListener typedListener = listener as ICommandListener;
			if (typedListener != null) typedListener.ExitArg(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICommandVisitor<TResult> typedVisitor = visitor as ICommandVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArg(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ArgContext arg() {
		ArgContext _localctx = new ArgContext(Context, State);
		EnterRule(_localctx, 2, RULE_arg);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 42;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 41;
				str();
				}
				}
				State = 44;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( (((_la) & ~0x3f) == 0 && ((1L << _la) & 188L) != 0) );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RedContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Red_opContext red_op() {
			return GetRuleContext<Red_opContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ArgContext arg() {
			return GetRuleContext<ArgContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Red_streamContext red_stream() {
			return GetRuleContext<Red_streamContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] WS() { return GetTokens(CommandParser.WS); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WS(int i) {
			return GetToken(CommandParser.WS, i);
		}
		public RedContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_red; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ICommandListener typedListener = listener as ICommandListener;
			if (typedListener != null) typedListener.EnterRed(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ICommandListener typedListener = listener as ICommandListener;
			if (typedListener != null) typedListener.ExitRed(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICommandVisitor<TResult> typedVisitor = visitor as ICommandVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRed(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public RedContext red() {
		RedContext _localctx = new RedContext(Context, State);
		EnterRule(_localctx, 4, RULE_red);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 47;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==NUMBER) {
				{
				State = 46;
				red_stream();
				}
			}

			State = 49;
			red_op();
			State = 53;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==WS) {
				{
				{
				State = 50;
				Match(WS);
				}
				}
				State = 55;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 56;
			arg();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Red_streamContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] NUMBER() { return GetTokens(CommandParser.NUMBER); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER(int i) {
			return GetToken(CommandParser.NUMBER, i);
		}
		public Red_streamContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_red_stream; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ICommandListener typedListener = listener as ICommandListener;
			if (typedListener != null) typedListener.EnterRed_stream(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ICommandListener typedListener = listener as ICommandListener;
			if (typedListener != null) typedListener.ExitRed_stream(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICommandVisitor<TResult> typedVisitor = visitor as ICommandVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRed_stream(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Red_streamContext red_stream() {
		Red_streamContext _localctx = new Red_streamContext(Context, State);
		EnterRule(_localctx, 6, RULE_red_stream);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 59;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 58;
				Match(NUMBER);
				}
				}
				State = 61;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==NUMBER );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Red_opContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] REDIRECT() { return GetTokens(CommandParser.REDIRECT); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode REDIRECT(int i) {
			return GetToken(CommandParser.REDIRECT, i);
		}
		public Red_opContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_red_op; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ICommandListener typedListener = listener as ICommandListener;
			if (typedListener != null) typedListener.EnterRed_op(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ICommandListener typedListener = listener as ICommandListener;
			if (typedListener != null) typedListener.ExitRed_op(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICommandVisitor<TResult> typedVisitor = visitor as ICommandVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRed_op(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Red_opContext red_op() {
		Red_opContext _localctx = new Red_opContext(Context, State);
		EnterRule(_localctx, 8, RULE_red_op);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 63;
			Match(REDIRECT);
			State = 65;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==REDIRECT) {
				{
				State = 64;
				Match(REDIRECT);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StrContext : ParserRuleContext {
		public StrContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_str; } }
	 
		public StrContext() { }
		public virtual void CopyFrom(StrContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class DoubleQuotedStringContext : StrContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] DQUOTE() { return GetTokens(CommandParser.DQUOTE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DQUOTE(int i) {
			return GetToken(CommandParser.DQUOTE, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Dstr_innerContext[] dstr_inner() {
			return GetRuleContexts<Dstr_innerContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Dstr_innerContext dstr_inner(int i) {
			return GetRuleContext<Dstr_innerContext>(i);
		}
		public DoubleQuotedStringContext(StrContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ICommandListener typedListener = listener as ICommandListener;
			if (typedListener != null) typedListener.EnterDoubleQuotedString(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ICommandListener typedListener = listener as ICommandListener;
			if (typedListener != null) typedListener.ExitDoubleQuotedString(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICommandVisitor<TResult> typedVisitor = visitor as ICommandVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDoubleQuotedString(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class SingleQuotedStringContext : StrContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] SQUOTE() { return GetTokens(CommandParser.SQUOTE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SQUOTE(int i) {
			return GetToken(CommandParser.SQUOTE, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Sstr_innerContext[] sstr_inner() {
			return GetRuleContexts<Sstr_innerContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Sstr_innerContext sstr_inner(int i) {
			return GetRuleContext<Sstr_innerContext>(i);
		}
		public SingleQuotedStringContext(StrContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ICommandListener typedListener = listener as ICommandListener;
			if (typedListener != null) typedListener.EnterSingleQuotedString(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ICommandListener typedListener = listener as ICommandListener;
			if (typedListener != null) typedListener.ExitSingleQuotedString(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICommandVisitor<TResult> typedVisitor = visitor as ICommandVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSingleQuotedString(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class UnquotedStringContext : StrContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] NON_WS() { return GetTokens(CommandParser.NON_WS); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NON_WS(int i) {
			return GetToken(CommandParser.NON_WS, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] NUMBER() { return GetTokens(CommandParser.NUMBER); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER(int i) {
			return GetToken(CommandParser.NUMBER, i);
		}
		public UnquotedStringContext(StrContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ICommandListener typedListener = listener as ICommandListener;
			if (typedListener != null) typedListener.EnterUnquotedString(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ICommandListener typedListener = listener as ICommandListener;
			if (typedListener != null) typedListener.ExitUnquotedString(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICommandVisitor<TResult> typedVisitor = visitor as ICommandVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitUnquotedString(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class EscapeCharacterContext : StrContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SLASH() { return GetToken(CommandParser.SLASH, 0); }
		public EscapeCharacterContext(StrContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ICommandListener typedListener = listener as ICommandListener;
			if (typedListener != null) typedListener.EnterEscapeCharacter(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ICommandListener typedListener = listener as ICommandListener;
			if (typedListener != null) typedListener.ExitEscapeCharacter(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICommandVisitor<TResult> typedVisitor = visitor as ICommandVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEscapeCharacter(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StrContext str() {
		StrContext _localctx = new StrContext(Context, State);
		EnterRule(_localctx, 10, RULE_str);
		int _la;
		try {
			int _alt;
			State = 90;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case SLASH:
				_localctx = new EscapeCharacterContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 67;
				Match(SLASH);
				State = 68;
				MatchWildcard();
				}
				break;
			case NUMBER:
			case NON_WS:
				_localctx = new UnquotedStringContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 70;
				ErrorHandler.Sync(this);
				_alt = 1;
				do {
					switch (_alt) {
					case 1:
						{
						{
						State = 69;
						_la = TokenStream.LA(1);
						if ( !(_la==NUMBER || _la==NON_WS) ) {
						ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						}
						}
						break;
					default:
						throw new NoViableAltException(this);
					}
					State = 72;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,9,Context);
				} while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER );
				}
				break;
			case SQUOTE:
				_localctx = new SingleQuotedStringContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 74;
				Match(SQUOTE);
				State = 78;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 250L) != 0)) {
					{
					{
					State = 75;
					sstr_inner();
					}
					}
					State = 80;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 81;
				Match(SQUOTE);
				}
				break;
			case DQUOTE:
				_localctx = new DoubleQuotedStringContext(_localctx);
				EnterOuterAlt(_localctx, 4);
				{
				State = 82;
				Match(DQUOTE);
				State = 86;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 246L) != 0)) {
					{
					{
					State = 83;
					dstr_inner();
					}
					}
					State = 88;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 89;
				Match(DQUOTE);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Sstr_innerContext : ParserRuleContext {
		public Sstr_innerContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_sstr_inner; } }
	 
		public Sstr_innerContext() { }
		public virtual void CopyFrom(Sstr_innerContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class SingleStringTextContext : Sstr_innerContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] NON_WS() { return GetTokens(CommandParser.NON_WS); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NON_WS(int i) {
			return GetToken(CommandParser.NON_WS, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] WS() { return GetTokens(CommandParser.WS); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WS(int i) {
			return GetToken(CommandParser.WS, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] DQUOTE() { return GetTokens(CommandParser.DQUOTE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DQUOTE(int i) {
			return GetToken(CommandParser.DQUOTE, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] SLASH() { return GetTokens(CommandParser.SLASH); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SLASH(int i) {
			return GetToken(CommandParser.SLASH, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] NUMBER() { return GetTokens(CommandParser.NUMBER); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER(int i) {
			return GetToken(CommandParser.NUMBER, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] REDIRECT() { return GetTokens(CommandParser.REDIRECT); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode REDIRECT(int i) {
			return GetToken(CommandParser.REDIRECT, i);
		}
		public SingleStringTextContext(Sstr_innerContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ICommandListener typedListener = listener as ICommandListener;
			if (typedListener != null) typedListener.EnterSingleStringText(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ICommandListener typedListener = listener as ICommandListener;
			if (typedListener != null) typedListener.ExitSingleStringText(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICommandVisitor<TResult> typedVisitor = visitor as ICommandVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSingleStringText(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Sstr_innerContext sstr_inner() {
		Sstr_innerContext _localctx = new Sstr_innerContext(Context, State);
		EnterRule(_localctx, 12, RULE_sstr_inner);
		int _la;
		try {
			int _alt;
			_localctx = new SingleStringTextContext(_localctx);
			EnterOuterAlt(_localctx, 1);
			{
			State = 93;
			ErrorHandler.Sync(this);
			_alt = 1;
			do {
				switch (_alt) {
				case 1:
					{
					{
					State = 92;
					_la = TokenStream.LA(1);
					if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 250L) != 0)) ) {
					ErrorHandler.RecoverInline(this);
					}
					else {
						ErrorHandler.ReportMatch(this);
					    Consume();
					}
					}
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				State = 95;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,13,Context);
			} while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Dstr_innerContext : ParserRuleContext {
		public Dstr_innerContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_dstr_inner; } }
	 
		public Dstr_innerContext() { }
		public virtual void CopyFrom(Dstr_innerContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class DoubleStringEscapeCharacterContext : Dstr_innerContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SLASH() { return GetToken(CommandParser.SLASH, 0); }
		public DoubleStringEscapeCharacterContext(Dstr_innerContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ICommandListener typedListener = listener as ICommandListener;
			if (typedListener != null) typedListener.EnterDoubleStringEscapeCharacter(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ICommandListener typedListener = listener as ICommandListener;
			if (typedListener != null) typedListener.ExitDoubleStringEscapeCharacter(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICommandVisitor<TResult> typedVisitor = visitor as ICommandVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDoubleStringEscapeCharacter(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class DoubleStringTextContext : Dstr_innerContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] NON_WS() { return GetTokens(CommandParser.NON_WS); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NON_WS(int i) {
			return GetToken(CommandParser.NON_WS, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] WS() { return GetTokens(CommandParser.WS); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WS(int i) {
			return GetToken(CommandParser.WS, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] SQUOTE() { return GetTokens(CommandParser.SQUOTE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SQUOTE(int i) {
			return GetToken(CommandParser.SQUOTE, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] NUMBER() { return GetTokens(CommandParser.NUMBER); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER(int i) {
			return GetToken(CommandParser.NUMBER, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] REDIRECT() { return GetTokens(CommandParser.REDIRECT); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode REDIRECT(int i) {
			return GetToken(CommandParser.REDIRECT, i);
		}
		public DoubleStringTextContext(Dstr_innerContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ICommandListener typedListener = listener as ICommandListener;
			if (typedListener != null) typedListener.EnterDoubleStringText(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ICommandListener typedListener = listener as ICommandListener;
			if (typedListener != null) typedListener.ExitDoubleStringText(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICommandVisitor<TResult> typedVisitor = visitor as ICommandVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDoubleStringText(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Dstr_innerContext dstr_inner() {
		Dstr_innerContext _localctx = new Dstr_innerContext(Context, State);
		EnterRule(_localctx, 14, RULE_dstr_inner);
		int _la;
		try {
			int _alt;
			State = 104;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case SLASH:
				_localctx = new DoubleStringEscapeCharacterContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 97;
				Match(SLASH);
				State = 98;
				MatchWildcard();
				}
				break;
			case WS:
			case SQUOTE:
			case NUMBER:
			case REDIRECT:
			case NON_WS:
				_localctx = new DoubleStringTextContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 100;
				ErrorHandler.Sync(this);
				_alt = 1;
				do {
					switch (_alt) {
					case 1:
						{
						{
						State = 99;
						_la = TokenStream.LA(1);
						if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 230L) != 0)) ) {
						ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						}
						}
						break;
					default:
						throw new NoViableAltException(this);
					}
					State = 102;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,14,Context);
				} while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER );
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static int[] _serializedATN = {
		4,1,7,107,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,1,0,1,0,4,0,19,8,0,11,0,12,0,20,1,0,5,0,24,8,0,10,0,12,0,27,9,0,1,
		0,4,0,30,8,0,11,0,12,0,31,1,0,5,0,35,8,0,10,0,12,0,38,9,0,1,0,1,0,1,1,
		4,1,43,8,1,11,1,12,1,44,1,2,3,2,48,8,2,1,2,1,2,5,2,52,8,2,10,2,12,2,55,
		9,2,1,2,1,2,1,3,4,3,60,8,3,11,3,12,3,61,1,4,1,4,3,4,66,8,4,1,5,1,5,1,5,
		4,5,71,8,5,11,5,12,5,72,1,5,1,5,5,5,77,8,5,10,5,12,5,80,9,5,1,5,1,5,1,
		5,5,5,85,8,5,10,5,12,5,88,9,5,1,5,3,5,91,8,5,1,6,4,6,94,8,6,11,6,12,6,
		95,1,7,1,7,1,7,4,7,101,8,7,11,7,12,7,102,3,7,105,8,7,1,7,0,0,8,0,2,4,6,
		8,10,12,14,0,3,2,0,5,5,7,7,2,0,1,1,3,7,2,0,1,2,5,7,116,0,16,1,0,0,0,2,
		42,1,0,0,0,4,47,1,0,0,0,6,59,1,0,0,0,8,63,1,0,0,0,10,90,1,0,0,0,12,93,
		1,0,0,0,14,104,1,0,0,0,16,25,3,2,1,0,17,19,5,1,0,0,18,17,1,0,0,0,19,20,
		1,0,0,0,20,18,1,0,0,0,20,21,1,0,0,0,21,22,1,0,0,0,22,24,3,2,1,0,23,18,
		1,0,0,0,24,27,1,0,0,0,25,23,1,0,0,0,25,26,1,0,0,0,26,36,1,0,0,0,27,25,
		1,0,0,0,28,30,5,1,0,0,29,28,1,0,0,0,30,31,1,0,0,0,31,29,1,0,0,0,31,32,
		1,0,0,0,32,33,1,0,0,0,33,35,3,4,2,0,34,29,1,0,0,0,35,38,1,0,0,0,36,34,
		1,0,0,0,36,37,1,0,0,0,37,39,1,0,0,0,38,36,1,0,0,0,39,40,5,0,0,1,40,1,1,
		0,0,0,41,43,3,10,5,0,42,41,1,0,0,0,43,44,1,0,0,0,44,42,1,0,0,0,44,45,1,
		0,0,0,45,3,1,0,0,0,46,48,3,6,3,0,47,46,1,0,0,0,47,48,1,0,0,0,48,49,1,0,
		0,0,49,53,3,8,4,0,50,52,5,1,0,0,51,50,1,0,0,0,52,55,1,0,0,0,53,51,1,0,
		0,0,53,54,1,0,0,0,54,56,1,0,0,0,55,53,1,0,0,0,56,57,3,2,1,0,57,5,1,0,0,
		0,58,60,5,5,0,0,59,58,1,0,0,0,60,61,1,0,0,0,61,59,1,0,0,0,61,62,1,0,0,
		0,62,7,1,0,0,0,63,65,5,6,0,0,64,66,5,6,0,0,65,64,1,0,0,0,65,66,1,0,0,0,
		66,9,1,0,0,0,67,68,5,4,0,0,68,91,9,0,0,0,69,71,7,0,0,0,70,69,1,0,0,0,71,
		72,1,0,0,0,72,70,1,0,0,0,72,73,1,0,0,0,73,91,1,0,0,0,74,78,5,2,0,0,75,
		77,3,12,6,0,76,75,1,0,0,0,77,80,1,0,0,0,78,76,1,0,0,0,78,79,1,0,0,0,79,
		81,1,0,0,0,80,78,1,0,0,0,81,91,5,2,0,0,82,86,5,3,0,0,83,85,3,14,7,0,84,
		83,1,0,0,0,85,88,1,0,0,0,86,84,1,0,0,0,86,87,1,0,0,0,87,89,1,0,0,0,88,
		86,1,0,0,0,89,91,5,3,0,0,90,67,1,0,0,0,90,70,1,0,0,0,90,74,1,0,0,0,90,
		82,1,0,0,0,91,11,1,0,0,0,92,94,7,1,0,0,93,92,1,0,0,0,94,95,1,0,0,0,95,
		93,1,0,0,0,95,96,1,0,0,0,96,13,1,0,0,0,97,98,5,4,0,0,98,105,9,0,0,0,99,
		101,7,2,0,0,100,99,1,0,0,0,101,102,1,0,0,0,102,100,1,0,0,0,102,103,1,0,
		0,0,103,105,1,0,0,0,104,97,1,0,0,0,104,100,1,0,0,0,105,15,1,0,0,0,16,20,
		25,31,36,44,47,53,61,65,72,78,86,90,95,102,104
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace CodeCrafters.Shell.ArgParsing
